const makeWritten = (id, label, clarify, starter, example) => ({
  id, label, clarify,
  steps: [
    'Read the question and underline the product, user or process it names.',
    'Select the strongest evidence from the theory section or your own project work.',
    'Explain how that evidence answers the question; do not only list it.',
    'Check that each claim is specific, believable and connected to the design brief.'
  ],
  starter, example
});

const makeSection = (title, html, facts, written) => ({ title, html, facts, written });

const COURSE_MODULES = [
  {
    id: 1,
    title: 'Textiles with a purpose',
    subtitle: 'Discover how textiles work, why hats matter and how a product can communicate a cause.',
    sections: [
      makeSection('1.1 Textiles are everywhere', `
        <p><strong>Textiles</strong> are materials made from fibres, yarns or fabric. They appear in clothing, furnishings, transport, sport, health care, safety equipment and many everyday products. A textile product is designed by matching a material's properties to a purpose.</p>
        <p>A bucket hat is an apparel textile product. Its fabric, shape, seams, brim, lining and decoration work together as a system. The product must be wearable and durable while also communicating the designer's intention.</p>`, [
        ['What are textiles?', 'Materials made from fibres, yarns or fabric', 'Only clothes', 'Any hard plastic object', 'Which item is a textile product?', 'A fabric school bag', 'A glass beaker', 'A steel ruler'],
        ['What should guide material selection?', 'The product purpose and needed properties', 'The alphabetic order of fabrics', 'The colour of the worksheet', 'A rain hat needs water resistance. What should the designer compare?', 'Fabric properties', 'Page margins', 'Student surnames'],
        ['Which statement describes a bucket hat as a system?', 'Its fabric, shape, seams, brim, lining and decoration interact', 'Only the logo matters', 'Every part works independently', 'If the brim collapses, what is affected?', 'The function of the whole hat', 'Only the title page', 'The classroom clock'],
        ['What is an apparel textile product?', 'A textile product worn on the body', 'A timber product', 'A food product', 'Which is apparel?', 'A bucket hat', 'A tea towel', 'A curtain'],
        ['Why learn textile vocabulary?', 'It helps describe materials, processes and decisions precisely', 'It replaces practical work', 'It makes all fabrics identical', 'A student must justify a fabric choice. What helps most?', 'Accurate textile terms', 'A random adjective', 'A blank label']
      ], makeWritten('m1-s1', 'Explain why a bucket hat is a textile system, not just a piece of fabric.', 'Identify at least three interacting parts and explain what each contributes.', 'A bucket hat works as a system because …', 'A sports bag works as a textile system because the strong outer fabric carries loads, the zip controls access and the seams hold the panels together.')),
      makeSection('1.2 Hats, users and sun protection', `
        <p>Hats can provide shade, warmth, protection, cultural meaning, identity or fashion. A bucket hat has a crown that fits the head and a surrounding brim. Its effectiveness depends on fit, coverage, fabric and how it is worn.</p>
        <p>Sun protection is one valid design motive, but the hat is only one part of a broader sun-safe routine. Students must follow current school and health guidance rather than treating a hat as complete protection on its own.</p>`, [
        ['What can a hat provide?', 'Shade, protection, identity or fashion', 'Guaranteed complete sun protection', 'Only decoration', 'A user needs more shade around the face. Which feature matters?', 'Brim coverage', 'Thread colour alone', 'The portfolio font'],
        ['What part fits around the head?', 'The crown', 'The bobbin', 'The seam ripper', 'Which part surrounds a bucket hat?', 'The brim', 'The presser foot', 'The grainline'],
        ['Why must fit be considered?', 'A hat must stay comfortably and appropriately on the intended user', 'One size always suits everyone', 'Fit affects only the drawing', 'A hat slips over the user’s eyes. What has failed?', 'Fit and function', 'The colour chart', 'The mood-board title'],
        ['Is a hat the whole sun-safe routine?', 'No, it is one part of broader sun protection', 'Yes, always', 'Only on cloudy days', 'What should a student do about sun-safety requirements?', 'Follow current school and health guidance', 'Invent a rule', 'Ignore teacher direction'],
        ['What makes a design motive useful?', 'It connects a real user need to product decisions', 'It is vague and untestable', 'It copies a logo', 'A student designs for outdoor use. What should be explained?', 'How choices respond to that use', 'Only the student’s favourite colour', 'The file name']
      ], makeWritten('m1-s2', 'Describe one intended user and explain two hat features that could respond to their needs.', 'Name the user, the need and the connection between each feature and that need.', 'My intended user needs …, so the hat should …', 'A gardener needs a secure, comfortable hat, so an adjustable internal band and an even brim would support fit and coverage.')),
      makeSection('1.3 Designing for a cause', `
        <p>Visual communication uses colour, imagery, symbols, words and materials to convey meaning. In this project, the reversible bucket hat may communicate an environmental, health, social or identity-based cause chosen within teacher guidance.</p>
        <p>A cause should be researched respectfully. Avoid copying protected artwork, community symbols or campaign branding without permission. The design should communicate a clear message while remaining functional, wearable and appropriate for its audience.</p>`, [
        ['What is visual communication?', 'Using visual choices to convey meaning', 'Speaking louder', 'Adding decoration without purpose', 'Which choice can communicate meaning?', 'A deliberately selected colour and symbol', 'A random file name', 'A blank page'],
        ['What kinds of causes may guide the hat?', 'Environmental, health, social or identity-based causes', 'Only commercial brands', 'Only sports teams', 'A student chooses a health message. What comes next?', 'Respectful research and design development', 'Copying a campaign logo', 'Skipping the user'],
        ['Why avoid copying protected cultural artwork?', 'Respect, permission and cultural ownership matter', 'It is always too colourful', 'It cannot be sewn', 'A symbol belongs to a particular community. What should the student do?', 'Seek guidance and avoid unauthorised use', 'Trace it immediately', 'Remove all research notes'],
        ['What else must a message-based hat remain?', 'Functional, wearable and audience-appropriate', 'Only visually complex', 'Impossible to understand', 'A powerful graphic makes the brim unusable. Is the design successful?', 'No, function and message must work together', 'Yes, graphics replace function', 'Only if the file is large'],
        ['What makes a message clear?', 'Consistent choices linked to the intended meaning', 'Many unrelated symbols', 'Every colour at once', 'Which design is clearer?', 'A focused symbol and colour system explained by the designer', 'A collage with no link to the brief', 'An unlabelled copy']
      ], makeWritten('m1-s3', 'Propose a respectful cause or message for a hat and explain how it could be communicated.', 'State the message, intended audience and two visual choices without copying an existing campaign.', 'My hat could communicate … to … by using …', 'A reusable lunch wrap could communicate waste reduction through a repeated leaf motif and a limited green-and-earth palette, without copying an organisation’s logo.'))
    ]
  },
  {
    id: 2,
    title: 'Safe textile work',
    subtitle: 'Control risks, organise the workspace and use tools only after teacher instruction.',
    sections: [
      makeSection('2.1 Practical-room routines', `
        <p>Safe work begins before a tool is used. Follow teacher instructions, wear the required protective clothing and enclosed footwear, secure hair and loose clothing, remove or control jewellery, and keep bags and walkways clear.</p>
        <p>Report damaged equipment, frayed cords, spills, broken needles or uncertainty immediately. Do not start practical work without teacher permission. Local classroom rules and approved safety training remain authoritative.</p>`, [
        ['When does safe work begin?', 'Before any tool is used', 'After packing up', 'Only after an accident', 'A bag blocks a walkway. What should happen?', 'Move it to the approved storage place', 'Step over it', 'Hide it under a machine pedal'],
        ['Why secure hair and loose clothing?', 'They can catch in equipment', 'They change fabric colour', 'They improve stitch length', 'A loose sleeve is near a machine. What is the control?', 'Secure it before sewing', 'Sew faster', 'Turn off the room lights'],
        ['What should happen to damaged equipment?', 'Stop and report it to the teacher', 'Use it carefully', 'Ask another student to test it', 'A cord is frayed. What is the correct response?', 'Do not use it; report it', 'Tape it without permission', 'Pull it from the wall by the cord'],
        ['When may practical work begin?', 'After teacher instruction and permission', 'As soon as a student enters', 'Whenever a machine is free', 'The teacher is outside the room. Should a student start sewing?', 'No', 'Yes, if experienced', 'Only at full speed'],
        ['What has priority when rules differ?', 'The current teacher-approved classroom procedure', 'A social-media tutorial', 'A student guess', 'A web video shows a different setup. What should the student follow?', 'Teacher instruction for the actual room and machine', 'The fastest method online', 'Whichever looks easier']
      ], makeWritten('m2-s1', 'Write a practical-room entry routine that controls five common risks.', 'Order the controls from entering the room to being ready for teacher approval.', 'Before I begin practical work, I will …', 'Before using a drill press, a student would secure loose clothing, check the area, inspect the tool, wear required PPE and wait for teacher approval.')),
      makeSection('2.2 Tools, pins, shears and irons', `
        <p>Select each tool for its intended job. Fabric shears cut fabric; paper scissors cut paper; pins temporarily hold layers; a seam ripper removes stitches; marking tools transfer approved guides; and an iron presses fabric and seams when the material and settings are suitable.</p>
        <p>Carry scissors closed with the point down as directed, store pins and needles in a container, never place them in your mouth, and keep fingers away from sharp points. Steam and hot soleplates can burn. Use the iron only after demonstration and return it to the approved safe position.</p>`, [
        ['What should fabric shears cut?', 'Fabric only', 'Paper patterns', 'Electrical cord', 'A student needs to cut a paper template. Which tool?', 'Paper scissors', 'Fabric shears', 'Seam ripper'],
        ['What is a seam ripper for?', 'Removing stitches carefully', 'Cutting pattern pieces', 'Winding a bobbin', 'A seam must be corrected. Which tool suits the task?', 'A seam ripper used as instructed', 'An iron', 'A pin cushion'],
        ['Where should pins and needles be stored?', 'In an approved container or pin cushion', 'In the mouth', 'Loose on the floor', 'A pin falls. What should happen?', 'Stop and retrieve or report it safely', 'Kick it under the table', 'Leave it for later'],
        ['What can cause an iron injury?', 'Steam and the hot soleplate', 'A cool tape measure', 'A folded paper pattern', 'What must be checked before pressing?', 'The material, setting and teacher-approved procedure', 'The student’s favourite colour', 'The class roll'],
        ['How should scissors be carried?', 'Closed and directed safely as taught', 'Open above shoulder height', 'Hidden in fabric', 'A student walks with open shears. What is wrong?', 'The blades create an avoidable sharp hazard', 'The handles are too dark', 'The fabric may wrinkle']
      ], makeWritten('m2-s2', 'Choose four textile tools and justify their use and one safety control for each.', 'Use the pattern: tool → intended function → specific control.', 'I would use … because …; the key control is …', 'A craft knife can cut card accurately, but it must be used on a cutting mat with the approved grip and teacher supervision.')),
      makeSection('2.3 Sewing-machine safety', `
        <p>A sewing machine forms stitches rapidly with a moving needle and feed mechanism. Keep fingers clear of the needle and presser foot, maintain a stable seated posture, guide rather than pull the fabric, and sew only at a speed you can control.</p>
        <p>Threading, bobbin setup, needle changes and fault finding must follow the instructions for the actual classroom machine. Switch the machine off when it is not being used or before teacher-approved adjustments. Stop immediately if the sound, stitch formation or machine movement is abnormal.</p>`, [
        ['Where should fingers stay?', 'Clear of the needle and presser foot', 'Under the presser foot', 'On the hand wheel while sewing', 'Fabric is approaching a curve. What should the student do?', 'Slow down and guide it with fingers safely clear', 'Pull hard', 'Press the pedal fully'],
        ['Should fabric be pulled through the machine?', 'No, guide it while the feed system moves it', 'Yes, always', 'Only by the thread', 'Stitches are becoming uneven because fabric is dragged. What is the likely issue?', 'The student is interfering with the feed', 'The hat colour', 'The chair label'],
        ['When should the machine be switched off?', 'When not in use and before approved adjustments', 'Only at the end of term', 'Never', 'A thread tangle appears. What is the first response?', 'Stop and switch off as directed', 'Keep sewing faster', 'Pull the needle sideways'],
        ['Which instructions control threading?', 'Instructions for the actual classroom machine', 'Any online machine', 'A friend’s guess', 'Two machine models differ. What should the student do?', 'Use the demonstrated sequence for the assigned machine', 'Combine both sequences', 'Skip the bobbin'],
        ['What should happen if the machine sounds abnormal?', 'Stop and ask the teacher', 'Increase speed', 'Ignore it', 'The needle begins striking the plate. What is safest?', 'Stop immediately', 'Hold the needle', 'Force the fabric through']
      ], makeWritten('m2-s3', 'Explain how a student should prepare, operate and stop a sewing machine safely.', 'Describe the sequence, not just a list of isolated rules.', 'A safe machine routine begins by …', 'A safe laser-cutter routine begins with teacher approval, a material check and a clear work area; operation is monitored, and any fault causes an immediate stop.'))
    ]
  },
  {
    id: 3,
    title: 'Visual messages',
    subtitle: 'Use colour, imagery and symbols deliberately and respectfully.',
    sections: [
      makeSection('3.1 Colour communicates', `
        <p>Colour can attract attention, organise information, create contrast and suggest associations. Meanings are not universal: culture, context, age, fashion and personal experience can change how a colour is interpreted.</p>
        <p>Build a limited palette that supports the intended message and remains legible on fabric. Test the real fabric because screen colours, printed samples and dyed textiles can appear different.</p>`, [
        ['Are colour meanings universal?', 'No, context and culture affect interpretation', 'Yes, everywhere', 'Only in fashion', 'Why test colour with the intended audience?', 'People may interpret it differently', 'To avoid all explanation', 'To change the project brief'],
        ['What can colour do?', 'Create contrast and support a message', 'Replace safe construction', 'Guarantee meaning', 'A symbol disappears into its background. What is needed?', 'More colour contrast', 'More unrelated colours', 'A smaller brim'],
        ['Why use a limited palette?', 'It can make the message more coherent', 'It removes all choice', 'It makes fabric stronger', 'Which palette is likely clearer?', 'Three related colours with deliberate contrast', 'Every available colour without a reason', 'Two identical low-contrast colours'],
        ['Why test real fabric?', 'Screen, print and fabric colours can differ', 'Fabric has no colour', 'Screens are always exact', 'A digital purple prints as dull grey. What does this show?', 'Materials and processes change appearance', 'The user is wrong', 'Colour theory is useless'],
        ['What should justify a colour choice?', 'Its connection to message, audience and context', 'Personal preference alone', 'Its file size', 'A student selects blue. What makes the choice defensible?', 'Explaining how the audience may read it', 'Saying only “I like it”', 'Using blue in every section']
      ], makeWritten('m3-s1', 'Select a three-colour palette and justify how it could support a chosen message.', 'Explain the role of each colour and acknowledge that meaning depends on context.', 'My palette uses … because …', 'A road-safety poster might use high-contrast yellow and black for visibility, with white space to keep the warning readable.')),
      makeSection('3.2 Symbols and imagery', `
        <p>A <strong>symbol</strong> is a simplified visual that carries an idea. Imagery may be literal, abstract or pattern-based. Effective symbols are recognisable at the scale and distance where the product will be seen.</p>
        <p>Before selecting a symbol, research its meaning and ownership. Simplify detail for stitching, appliqué, stencil or vinyl, then prototype it at the actual size. Avoid stereotypes and unauthorised cultural or campaign marks.</p>`, [
        ['What is a symbol?', 'A visual that carries an idea', 'A stitch error', 'A material list', 'Which symbol will read best from a distance?', 'A clear simplified shape', 'A tiny detailed photograph', 'An invisible outline'],
        ['Why prototype at actual size?', 'Detail and legibility change with scale', 'The hat becomes larger', 'It replaces research', 'Fine lines vanish in stitching. What should change?', 'Simplify and thicken the design', 'Add smaller details', 'Ignore the sample'],
        ['What must be researched?', 'Meaning, context and ownership', 'Only the download size', 'Only the designer’s initials', 'A culturally specific motif is found online. What is responsible?', 'Seek guidance and permission; do not assume free use', 'Copy it immediately', 'Change one colour and claim ownership'],
        ['How can imagery be organised?', 'As literal, abstract or repeated pattern forms', 'Only as logos', 'Only as text', 'A repeated leaf shape around a brim is what kind of use?', 'Pattern-based imagery', 'A machine setting', 'A seam allowance'],
        ['What connects technique and symbol design?', 'The symbol must suit how it will be made', 'Any detail works in every technique', 'Technique affects only cost', 'Which symbol suits appliqué best?', 'A bold shape with manageable edges', 'Many hairline details', 'A photographic gradient']
      ], makeWritten('m3-s2', 'Describe a symbol for your message and explain how you would make it readable on fabric.', 'Cover meaning, ownership, scale and the intended decorative technique.', 'The symbol represents …; I would adapt it by …', 'A recycling reminder could use three original curved arrows simplified into broad shapes so a stencil remains clear at small scale.')),
      makeSection('3.3 Analyse before you design', `
        <p>Designers analyse existing campaigns and products to understand how message, audience, colour, imagery, typography and placement work together. Analysis is not copying; it identifies strategies that can inform an original response.</p>
        <p>Use evidence: describe what is visible, interpret how it may affect the audience, then judge whether it is effective for its purpose. Compare more than one example so that a single campaign does not become the template for every idea.</p>`, [
        ['What is design analysis?', 'Studying how design choices work together', 'Copying an existing product', 'Listing colours only', 'A student names a logo but gives no explanation. What is missing?', 'Interpretation and judgement', 'A larger screenshot', 'A due date'],
        ['Why compare examples?', 'It reveals different strategies and reduces copying', 'It guarantees one answer', 'It removes the audience', 'Two campaigns use different tones. What can be learned?', 'Visual choices depend on purpose and audience', 'One must be wrong', 'Colour has no effect'],
        ['What is the evidence sequence?', 'Describe, interpret, judge', 'Judge, copy, submit', 'Draw, erase, ignore', '“The red shape is placed centrally” is what?', 'Description', 'A final judgement', 'A production step'],
        ['How is analysis different from copying?', 'It extracts principles for an original response', 'It reproduces every feature', 'There is no difference', 'What is a responsible use of inspiration?', 'Explain the strategy and create new imagery', 'Trace the logo', 'Remove the source note'],
        ['What should an effectiveness judgement reference?', 'Purpose and intended audience', 'Only personal taste', 'The designer’s file name', 'A campaign is attractive but confusing. What should be judged?', 'Whether it communicates the intended message', 'Whether it uses enough colours', 'Whether it prints on A4']
      ], makeWritten('m3-s3', 'Analyse one existing message-based design using describe, interpret and judge.', 'Separate what you can see from what you infer, then link the judgement to audience and purpose.', 'I can see …; this may suggest …; it is effective because …', 'A library poster uses one large open-book image and a short heading. This focuses attention and is effective for students moving past quickly.'))
    ]
  },
  {
    id: 4,
    title: 'Define the challenge',
    subtitle: 'Turn a context and need into a focused design brief and testable criteria.',
    sections: [
      makeSection('4.1 Design situation, need and user', `
        <p>A <strong>design situation</strong> explains the context, need or opportunity and intended user. It gives enough background to understand why a solution is required without deciding the solution too early.</p>
        <p>Research the user's physical, emotional, practical and communication needs. Distinguish evidence from assumptions, and check sensitive ideas with the teacher before developing them.</p>`, [
        ['What does a design situation explain?', 'Context, need and intended user', 'Only the final colour', 'Every construction step', 'Which comes before choosing the solution?', 'Understanding the situation and user', 'Sewing the brim', 'Writing the evaluation'],
        ['Why avoid deciding too early?', 'It can close off better responses to the real need', 'Designers should never choose', 'It changes fabric grain', 'A student chooses decoration before identifying the user. What is missing?', 'User-centred definition', 'A bobbin', 'A presentation'],
        ['What kinds of user needs may matter?', 'Physical, emotional, practical and communication needs', 'Only favourite colour', 'Only age', 'A user has sensory sensitivities. What might be researched?', 'Comfort, texture and fit preferences', 'The class printer', 'The folder name'],
        ['What is an assumption?', 'A belief not yet supported by evidence', 'A measured fact', 'A teacher instruction', '“All teenagers like neon colours” is what?', 'An unsupported assumption', 'A test result', 'A material property'],
        ['When should sensitive ideas be checked?', 'Before they are developed or represented publicly', 'After publication', 'Never', 'A cause involves grief. What is responsible?', 'Discuss audience and representation with the teacher', 'Use dramatic imagery immediately', 'Ask the internet to decide']
      ], makeWritten('m4-s1', 'Write a concise design situation for a chosen user and cause.', 'Include context, need and user without describing the finished hat in detail.', 'There is a need for … because …; the intended user is …', 'Students waiting outdoors need a calm wayfinding product because crowded signs are hard to read; the intended users include younger visitors.')),
      makeSection('4.2 A useful design brief', `
        <p>A <strong>design brief</strong> turns the situation into a clear task. It identifies the product, intended user, purpose and key qualities while leaving room for creative decisions.</p>
        <p>A useful brief is specific enough to guide work but not so narrow that only one solution is possible. Teacher-controlled requirements—approved pattern, practical sequence and safety processes—remain constraints even when they are not repeated in every sentence.</p>`, [
        ['What does a design brief do?', 'Turns a need into a clear design task', 'Records only evaluation', 'Lists marks and dates', 'Which belongs in a brief?', 'Product, user, purpose and key qualities', 'Every machine part number', 'A copied logo'],
        ['Why leave creative room?', 'Different solutions may meet the same need', 'The task should be vague', 'Criteria do not matter', 'Which brief is stronger?', 'Design a reversible bucket hat for a defined user that communicates a chosen cause', 'Make something nice', 'Copy this exact hat'],
        ['What remains a constraint?', 'Teacher-approved safety and practical requirements', 'Any social media suggestion', 'The colour of the browser', 'A pattern is specified by the teacher. How should it be treated?', 'As an authorised project constraint', 'As optional decoration', 'As a student name'],
        ['What makes a brief too narrow?', 'It specifies every feature before investigation', 'It identifies a user', 'It states a purpose', 'A brief dictates exact colours and symbols without reason. What risk?', 'It prevents meaningful design development', 'It improves all creativity', 'It changes the fibre type'],
        ['How should a brief be checked?', 'Against the situation, user and authorised requirements', 'Against a random product', 'Against the longest paragraph', 'The brief omits the intended user. What should happen?', 'Revise it before concept development', 'Continue and guess', 'Add more decoration']
      ], makeWritten('m4-s2', 'Write a design brief for your reversible bucket hat.', 'Include the product, intended user, communication purpose and two important qualities.', 'I will design and make … for … so that …; it must …', 'I will design and make a reusable fabric organiser for a student so that small tools stay visible; it must be durable and easy to open.')),
      makeSection('4.3 Criteria and constraints', `
        <p><strong>Criteria for success</strong> describe how the solution will be judged. Useful criteria are testable: fit, reversible function, construction quality, message clarity, comfort, durability and alignment with the brief.</p>
        <p><strong>Constraints</strong> are limits such as authorised materials, available equipment, lesson time, skill level, teacher-approved processes and the supplied pattern. Do not invent dimensions or material quantities; record actual teacher directions and project observations.</p>`, [
        ['What are criteria?', 'Testable qualities used to judge success', 'Unchangeable dates only', 'Decorative labels', 'Which is testable?', 'The hat reverses without exposed unfinished seams', 'The hat is good', 'The hat is cool'],
        ['What are constraints?', 'Real limits on the design and production', 'Reasons to stop thinking', 'Only colours', 'Which is a likely school constraint?', 'Available equipment and lesson time', 'Whether hats exist', 'The website background'],
        ['Why avoid invented dimensions?', 'The approved pattern and teacher directions control project facts', 'Measuring is never used', 'All hats are identical', 'A source does not state seam allowance. What should the site say?', 'Follow the approved pattern and teacher demonstration', 'Invent 10 mm', 'Use any value online'],
        ['What should criteria connect to?', 'The brief and user needs', 'A random rubric', 'The file title', 'Message clarity is a criterion. How could it be tested?', 'Ask intended viewers what message they perceive', 'Count the colours only', 'Measure the browser width'],
        ['Why record constraints early?', 'They shape realistic options and planning', 'They make evaluation unnecessary', 'They replace the user', 'A technique needs unavailable equipment. What should the designer do?', 'Choose or adapt a feasible technique', 'Assume the equipment will appear', 'Ignore the constraint']
      ], makeWritten('m4-s3', 'Write four testable criteria and three real constraints for your project.', 'Use measurable or observable language and separate evidence from assumptions.', 'My hat will be successful if …; a real constraint is …', 'A storage pouch will be successful if the zip opens smoothly ten times and the seams hold the intended tools; available fabric and lesson time are constraints.'))
    ]
  },
  {
    id: 5,
    title: 'Develop and select ideas',
    subtitle: 'Build a mood board, sketch distinct concepts and justify the strongest direction.',
    sections: [
      makeSection('5.1 Mood boards with direction', `
        <p>A mood board is a curated collection of images, colours, textures, materials, words and symbols that establishes a visual direction. It is more than a pile of attractive pictures: every element should connect to the theme, user or intended feeling.</p>
        <p>Arrange the board so relationships are visible. Add a short reflection explaining the theme, the strongest visual cues and how the board will guide the hat rather than becoming an end product by itself.</p>`, [
        ['What is a mood board?', 'A curated visual direction for a design', 'A final construction plan', 'A safety licence', 'Which belongs on a mood board?', 'Relevant colours, textures, images, words and symbols', 'Random unrelated screenshots', 'Machine fault codes'],
        ['What makes a board curated?', 'Elements are selected and connected deliberately', 'It contains the most images possible', 'It has no explanation', 'An image is attractive but unrelated. What should happen?', 'Remove it or justify a real connection', 'Make it larger', 'Duplicate it'],
        ['How does a mood board support design?', 'It guides later visual and material decisions', 'It replaces sketches', 'It sets machine tension', 'A palette and texture recur in sketches. What does this show?', 'The board is informing concept development', 'The board has failed', 'The pattern has changed'],
        ['What should the reflection explain?', 'Theme, visual cues and intended influence', 'Only where images came from', 'Only the page size', 'Which reflection is stronger?', 'The rough textures support resilience and the limited palette keeps the symbol clear', 'I like these pictures', 'This is my mood board'],
        ['Should the mood board be the final product?', 'No, it is a research and direction tool', 'Yes, always', 'Only if printed', 'What comes after a mood board?', 'Generate and test design concepts', 'Submit without sketches', 'Choose a random material']
      ], makeWritten('m5-s1', 'Plan a mood board and explain the five most useful elements you would include.', 'Link each element to the message, audience or intended feeling.', 'My mood board would include … because …', 'A calm study-space board could include muted blues, soft felt texture, rounded forms, quiet-library imagery and the word “focus”, each supporting a low-stimulation direction.')),
      makeSection('5.2 Distinct annotated concepts', `
        <p>Generate several genuinely different concepts before selecting one. Change the placement, scale, symbol, palette, decorative technique or relationship between the two reversible sides—not merely the title or one small colour.</p>
        <p>Annotations should communicate material, colour, technique, function, message and user benefit. Use arrows and concise notes. A rendered sketch adds believable colour and surface, while clear front/back or side A/side B views show how the reversible product works.</p>`, [
        ['Why create several concepts?', 'To explore different ways to meet the brief', 'To delay all decisions', 'To copy one idea repeatedly', 'What makes concepts distinct?', 'Meaningful changes in message, layout or technique', 'Different page borders only', 'The same design four times'],
        ['What should annotations explain?', 'Materials, technique, function, message and user benefit', 'Only the design number', 'Only the student name', '“Appliqué leaf reinforces the environmental message” is what?', 'A useful annotation', 'A file path', 'A safety hazard'],
        ['Why show both reversible sides?', 'Their relationship and separate functions must be understood', 'The hat has four crowns', 'One side is never used', 'Side A is detailed and side B is plain. What should be explained?', 'How each side supports the brief', 'Only which side is prettier', 'The browser history'],
        ['What is rendering?', 'Adding believable colour, tone or surface to communicate appearance', 'Writing a mark', 'Cutting fabric', 'A sketch has outlines only. What could improve communication?', 'Colour and texture rendering', 'More blank labels', 'A smaller title'],
        ['How should concepts link to the brief?', 'Each should respond to user, purpose, criteria and constraints', 'Only to personal taste', 'Only to the mood board', 'A concept cannot be made with available tools. What should happen?', 'Adapt or reject it using the constraints', 'Ignore feasibility', 'Invent new equipment']
      ], makeWritten('m5-s2', 'Describe three distinct hat concepts and the key difference between them.', 'Compare message, placement, palette and technique—not just appearance.', 'Concept 1 uses …, while Concept 2 …', 'Concept 1 for a lunch wrap uses a bold central stencil; Concept 2 uses a repeated appliqué border; Concept 3 relies on contrasting fabric panels and no added motif.')),
      makeSection('5.3 Feedback, PMI and final choice', `
        <p>Feedback is useful when it is specific, respectful and linked to criteria. Ask what is clear, what may confuse the user, what could improve function, and whether the intended message is understood.</p>
        <p>A PMI comparison records pluses, minuses and interesting possibilities. The final choice should be justified with evidence from the brief, criteria, prototypes and feedback. Selecting the highest score is not enough without explaining trade-offs and refinements.</p>`, [
        ['What makes feedback useful?', 'It is specific, respectful and linked to criteria', 'It gives only praise', 'It redesigns the work without explanation', 'Which feedback is actionable?', 'Increase contrast so the symbol reads from a distance', 'Looks cool', 'Change everything'],
        ['What does PMI mean?', 'Plus, Minus, Interesting', 'Plan, Measure, Iron', 'Pattern, Machine, Interfacing', 'Where would a possible new direction go?', 'Interesting', 'Only Minus', 'The title'],
        ['What should justify the final choice?', 'Evidence from brief, criteria, prototypes and feedback', 'A coin toss', 'The first sketch', 'A concept scores highest but has an unsafe process. What should happen?', 'Reject or revise it', 'Use it unchanged', 'Hide the risk'],
        ['What is a trade-off?', 'A gain in one area that may cost another', 'A free material', 'A copied symbol', 'Dense embroidery improves detail but adds time. This is what?', 'A trade-off', 'A universal rule', 'A spelling error'],
        ['How should feedback change a design?', 'Through a reasoned refinement', 'By following every comment', 'By removing the brief', 'Two peers disagree. What should guide the decision?', 'Criteria and intended user evidence', 'The loudest opinion', 'The shortest comment']
      ], makeWritten('m5-s3', 'Select one concept and justify it using criteria, feedback and one planned refinement.', 'Acknowledge a weakness or trade-off rather than claiming the idea is perfect.', 'I selected Concept … because …; feedback showed …, so I will …', 'I selected the zip pouch concept because it met the access and durability criteria. Feedback showed the pull tab was too small, so I will enlarge it before production.'))
    ]
  },
  {
    id: 6,
    title: 'Fibres, fabrics and sustainability',
    subtitle: 'Connect cotton and polyester properties to use, care and responsible decision-making.',
    sections: [
      makeSection('6.1 Fibre, yarn and fabric', `
        <p>A <strong>fibre</strong> is a fine strand. Fibres are twisted or otherwise combined into yarns; yarns can be woven, knitted or bonded into fabrics. Fabric structure and finishing affect stretch, strength, drape, handle and appearance.</p>
        <p>Woven fabric uses interlacing yarns and often provides stable pattern placement. Knitted fabric uses interlocking loops and usually stretches more. The approved hat pattern and teacher-selected materials determine what is suitable for this project.</p>`, [
        ['What is the sequence?', 'Fibre to yarn to fabric', 'Fabric to metal to yarn', 'Yarn to paper to fibre', 'What is a fibre?', 'A fine strand used to make textile structures', 'A complete garment', 'A machine setting'],
        ['How is woven fabric formed?', 'Interlacing yarns', 'Interlocking loops only', 'Melting timber', 'Which structure often gives stable pattern placement?', 'Woven fabric', 'Loose stuffing', 'A zipper'],
        ['How is knitted fabric formed?', 'Interlocking loops', 'Straight nails', 'Paper layers', 'Which structure usually stretches more?', 'Knitted fabric', 'Rigid card', 'A bobbin case'],
        ['What affects fabric behaviour?', 'Fibre, structure and finishing', 'Only colour', 'Only price', 'Two cotton fabrics behave differently. Why?', 'Their yarn, weave and finish may differ', 'Cotton has one fixed property', 'One is not fabric'],
        ['What controls project suitability?', 'Approved pattern, teacher guidance and tested material properties', 'Any online recommendation', 'The most expensive fabric', 'A stretchy knit distorts under the pattern. What should happen?', 'Stop and check the approved material choice', 'Cut it anyway', 'Pull it tighter']
      ], makeWritten('m6-s1', 'Explain the difference between fibre, yarn and fabric and why structure matters to a hat.', 'Use the production sequence and connect structure to one performance need.', 'A fibre is …; when fibres become …; the fabric structure matters because …', 'Wood fibres can become pulp and paper; the final sheet structure affects folding strength and surface finish.')),
      makeSection('6.2 Cotton and polyester', `
        <p>Cotton is a plant-based natural fibre valued for absorbency, comfort and dye uptake. Polyester is a manufactured synthetic fibre valued for strength, dimensional stability, quick drying and resistance to creasing. Actual performance depends on fabric construction and finish.</p>
        <p>Blends combine fibres to balance properties. Do not label one fibre “good” and the other “bad” without evidence. Compare the intended use, comfort, durability, care, available materials, decorative technique and teacher-approved construction.</p>`, [
        ['What type of fibre is cotton?', 'A natural plant fibre', 'A metal fibre', 'A glass fibre', 'Which property often supports dyeing?', 'Cotton absorbency and dye uptake', 'Cotton magnetism', 'Cotton waterproofing'],
        ['What type of fibre is polyester?', 'A manufactured synthetic fibre', 'An animal fibre', 'A timber product', 'Which property is often associated with polyester?', 'Quick drying and crease resistance', 'High water absorption only', 'Natural seed growth'],
        ['Why use a blend?', 'To combine or balance fibre properties', 'To remove all care needs', 'To guarantee sustainability', 'A cotton-polyester blend may aim to combine what?', 'Comfort with durability and easier care', 'Metal strength with timber grain', 'Only two colours'],
        ['Can fibre name alone predict everything?', 'No, construction and finish also matter', 'Yes, always', 'Only for white fabric', 'Two polyester fabrics have different drape. Why?', 'Structure and finishing differ', 'One label is false', 'Drape is random'],
        ['How should a fibre choice be justified?', 'Against use, properties, care, technique and constraints', 'By saying it is popular', 'By price alone', 'Cotton takes dye well but creases. What is this?', 'A property trade-off to consider', 'Proof it cannot be used', 'A machine fault']
      ], makeWritten('m6-s2', 'Compare cotton and polyester for a reversible bucket hat.', 'Use at least three relevant properties and make a balanced judgement.', 'Cotton may suit … because …, whereas polyester …; for this project …', 'Cardboard is easy to print and recycle in some systems, while plastic sheet resists moisture; the better choice depends on product life and recovery options.')),
      makeSection('6.3 Sustainability needs evidence', `
        <p>Sustainability includes environmental, social and economic considerations across raw material production, manufacturing, transport, use, care and end of life. A single recycled or natural label does not describe the whole system.</p>
        <p>Practical actions include using the authorised pattern efficiently, planning layout to reduce offcuts, caring for tools, making a durable product, reusing suitable remnants and recording real material choices. Claims about recycled polyester or cotton production should be supported by credible sources.</p>`, [
        ['What does sustainability include?', 'Environmental, social and economic considerations', 'Only colour choice', 'Only recycling', 'Which life-cycle stages matter?', 'Production, manufacture, use, care and end of life', 'Only purchase', 'Only disposal'],
        ['Does “natural” prove sustainable?', 'No, evidence across the system is needed', 'Yes, always', 'Only for cotton', 'Does “recycled” remove every impact?', 'No', 'Yes', 'Only if the fabric is purple'],
        ['How can layout reduce waste?', 'Place approved pattern pieces efficiently', 'Overlap pieces randomly', 'Cut before planning', 'What should happen to suitable remnants?', 'Reuse or store them as directed', 'Throw them on the floor', 'Hide them'],
        ['How does durability relate to sustainability?', 'A longer useful life can reduce replacement', 'It makes all production impact disappear', 'It changes the cause', 'A poorly made hat fails quickly. What has been reduced?', 'Product life and resource value', 'Only the mark', 'The colour palette'],
        ['What supports a sustainability claim?', 'A credible source and specific evidence', 'A green icon', 'A guess', 'A video claims bottles become polyester. What should a student record?', 'The process, source and a limitation or concern', 'Only the thumbnail', 'No evidence']
      ], makeWritten('m6-s3', 'Recommend one practical way to reduce material waste and one way to extend product life.', 'Keep the actions realistic for the authorised school project.', 'I can reduce waste by …; I can extend product life by …', 'A timber project can reduce waste through an efficient cutting list and extend product life by sealing exposed surfaces correctly.'))
    ]
  },
  {
    id: 7,
    title: 'Decorative technique trials',
    subtitle: 'Test, record and evaluate techniques before applying one to the final fabric.',
    sections: [
      makeSection('7.1 Sampling before production', `
        <p>A sample is a small controlled trial made before the final product. It lets the designer test material compatibility, colour, scale, stitch, adhesion, handling and safety without risking the final hat pieces.</p>
        <p>Use the actual or comparable fabric where possible. Label the technique, materials, steps, settings observed under teacher supervision, outcome and next change. Keep real machine settings and measurements as student observations—not invented website values.</p>`, [
        ['What is a sample?', 'A controlled trial before the final product', 'The final hat', 'A copied logo', 'Why sample first?', 'To test choices without risking final pieces', 'To avoid evaluation', 'To set assessment marks'],
        ['What should sample fabric be?', 'Actual or comparable to the final fabric', 'Always paper', 'Any random material', 'A technique works on felt but final fabric is thin cotton. What is needed?', 'A trial on the intended fabric', 'No more testing', 'A larger title'],
        ['What should a log record?', 'Technique, materials, steps, outcome and next change', 'Only the date', 'Only a photo', 'A sample puckers. What should be written?', 'The observed problem and planned adjustment', 'That it is perfect', 'Nothing'],
        ['Who controls machine settings?', 'Teacher demonstration and real observation', 'The website', 'A guessed standard', 'The source does not specify a setting. What should the site do?', 'Tell students to record the demonstrated setting', 'Invent a number', 'Remove safety guidance'],
        ['What makes a trial controlled?', 'Change and observe choices deliberately', 'Change everything at once', 'Avoid labels', 'Why test one variable at a time?', 'It helps identify what caused the outcome', 'It makes sewing faster', 'It removes the user']
      ], makeWritten('m7-s1', 'Plan a fair sample test for one decorative technique.', 'Name the fabric, controlled steps, evidence to record and one success criterion.', 'I will test … on … and keep … the same; I will record …', 'I will test two paper adhesives on identical card strips, keep size and pressure the same, and record bond strength and visible staining.')),
      makeSection('7.2 Appliqué, embroidery and couching', `
        <p><strong>Appliqué</strong> attaches a shaped fabric layer to a base. <strong>Embroidery</strong> builds imagery or texture with decorative stitches. <strong>Couching</strong> secures a thicker thread or cord onto the surface with smaller holding stitches.</p>
        <p>Each technique has different strengths. Bold appliqué shapes can communicate at distance; embroidery can add fine detail; couching can create strong lines and texture. Edges, backing, thread, stitch choice and placement must suit the fabric and teacher-approved process.</p>`, [
        ['What is appliqué?', 'A shaped fabric layer attached to a base', 'A woven edge only', 'A machine pedal', 'Which design suits appliqué?', 'A bold manageable shape', 'A photographic gradient', 'Invisible detail'],
        ['What is embroidery?', 'Decorative stitching used to build imagery or texture', 'Cutting a pattern', 'Winding fabric', 'Which technique may add fine stitched detail?', 'Embroidery', 'Paper cutting', 'Iron storage'],
        ['What is couching?', 'Securing thicker thread or cord to a surface', 'Joining two pattern pieces with a seam', 'Dyeing a whole fabric', 'Which technique creates a raised line?', 'Couching', 'A plain wash', 'A bobbin change'],
        ['What must technique suit?', 'Fabric, message, scale and approved process', 'Only personal preference', 'Only the colour wheel', 'Dense embroidery stiffens a brim. What should be reconsidered?', 'Scale, placement or technique', 'The intended user', 'The file name'],
        ['Why test edges and backing?', 'They affect durability, appearance and fabric behaviour', 'They are always hidden', 'They change marks', 'An appliqué edge lifts after handling. What failed?', 'Attachment durability', 'The mood board', 'The crown pattern']
      ], makeWritten('m7-s2', 'Choose between appliqué, embroidery and couching for a specific visual idea.', 'Compare at least two techniques before justifying one.', 'I would choose … rather than … because …', 'For a bold school-wayfinding arrow, cut vinyl may read more clearly than tiny hand lettering because its edges remain consistent at distance.')),
      makeSection('7.3 Stencilling, dyeing and transfers', `
        <p>Stencilling applies colour through an opening; dyeing changes fibre colour through an approved process; and iron-on or heat-transfer methods bond a prepared design to fabric. Suitability depends on fibre, fabric, equipment, permanence, surface feel and the required image.</p>
        <p>Heat, dyes, paints and cutting tools introduce specific risks. Follow teacher demonstrations, ventilation and protective controls. Test for bleeding, stiffness, adhesion, colour change and wash or wear durability as directed.</p>`, [
        ['What is stencilling?', 'Applying colour through a controlled opening', 'Joining seams', 'Winding thread', 'What helps keep a stencil image clear?', 'A secure stencil and controlled application', 'Flooding it with colour', 'Moving it repeatedly'],
        ['What does dyeing change?', 'The colour of suitable fibres or fabric', 'The pattern size', 'The bobbin case', 'Why does fibre type matter in dyeing?', 'Different fibres accept dyes differently', 'All fibres react identically', 'Fibre only affects price'],
        ['What does a heat transfer do?', 'Bonds a prepared design to fabric using an approved heat process', 'Grows cotton', 'Cuts a seam allowance', 'What must be checked before heat transfer?', 'Fabric suitability and teacher-approved settings', 'Only the graphic name', 'The room number'],
        ['What should a surface test observe?', 'Bleeding, stiffness, adhesion and durability', 'Only brightness', 'Only cost', 'Paint makes fabric too stiff. What does this affect?', 'Handle, comfort and function', 'The file format', 'The user’s name'],
        ['How are heat and chemical risks controlled?', 'Teacher demonstration, PPE and approved ventilation/processes', 'Guessing', 'Working faster', 'A dye process is unfamiliar. What should happen?', 'Stop and seek teacher instruction', 'Mix products', 'Copy an online recipe']
      ], makeWritten('m7-s3', 'Evaluate one decorative sample using Plus, Minus and Interesting.', 'Use observed evidence and name a precise next change.', 'A plus was …; a minus was …; it was interesting that …; next I would …', 'A stencil sample produced crisp outer edges, but the centre bled because too much paint was used. Next I would reduce paint and test on a fresh sample.'))
    ]
  },
  {
    id: 8,
    title: 'Prepare for production',
    subtitle: 'Read the approved pattern, prepare fabric accurately and prove machine readiness.',
    sections: [
      makeSection('8.1 Pattern pieces and symbols', `
        <p>A pattern communicates the shapes to cut and the information needed to align and assemble them. Common symbols may show grainline, fold, notches, cutting lines and placement. Use the actual teacher-approved bucket-hat pattern; generic online patterns are not substitutes.</p>
        <p>Identify each piece and the required quantity before cutting. Keep labels with pieces, transfer only the approved marks and ask if a symbol is unclear. Do not infer dimensions, seam allowances or piece orientation from a web page.</p>`, [
        ['What does a pattern communicate?', 'Shapes and assembly information', 'Assessment marks', 'Only decoration', 'Which source controls this project?', 'The teacher-approved pattern', 'Any online pattern', 'A generated diagram'],
        ['What can a grainline symbol indicate?', 'How a pattern piece aligns with the fabric grain', 'Where to write a name', 'The machine speed', 'Why identify grainline?', 'Orientation can affect shape and behaviour', 'It selects thread colour', 'It sets the due date'],
        ['What are notches for?', 'Matching related construction points', 'Cutting holes anywhere', 'Decorating the brim', 'Two curved pieces must align. What helps?', 'Transferred matching notches', 'A random fold', 'Extra glue'],
        ['What must be checked before cutting?', 'Piece identity, quantity, layout and teacher approval', 'Only colour', 'Only the first piece', 'A symbol is unclear. What should happen?', 'Stop and ask the teacher', 'Guess', 'Remove the symbol'],
        ['Should the website give invented dimensions?', 'No', 'Yes', 'Only if plausible', 'Why not?', 'Project facts belong to the approved pattern and demonstration', 'Measurements are unimportant', 'All patterns are the same']
      ], makeWritten('m8-s1', 'Explain how you will read and check the approved pattern before cutting.', 'Name at least four checks and the action you will take if information is unclear.', 'Before cutting, I will identify …, check … and ask …', 'Before laser cutting, a student would confirm material, file version, scale and quantity, then seek approval if any layer or dimension is unclear.')),
      makeSection('8.2 Layout, marking and cutting', `
        <p>Prepare fabric as demonstrated, identify right and wrong sides, align pattern pieces with grain or fold symbols, and arrange them efficiently without unauthorised overlap. Secure the pattern with the approved method and transfer only required marks.</p>
        <p>Cut smoothly with suitable tools and keep the fabric supported. Accuracy at this stage affects seam matching, crown shape and brim alignment. Keep paired and reversible-side pieces organised so they are not mixed.</p>`, [
        ['Why identify fabric sides?', 'Construction and decoration may use specific faces', 'Only for storage', 'It sets machine tension', 'Interfacing is applied to the wrong side. What must be known?', 'Which side is the wrong side', 'The student number', 'The mood-board colour'],
        ['Why plan layout?', 'To align pieces and reduce waste', 'To avoid the pattern', 'To add more seams', 'Can pattern pieces overlap?', 'Only if the approved pattern and teacher say so; normally no', 'Always', 'Whenever fabric is scarce'],
        ['What should be transferred?', 'Only approved construction marks', 'Every printed word', 'Random lines', 'Why keep marks controlled?', 'Extra marks can confuse construction or show on the product', 'They make fabric stronger', 'They improve sun protection'],
        ['How does cutting accuracy matter?', 'It affects how pieces and seams align', 'It changes only the folio', 'It does not matter on curves', 'A curved edge is jagged. What may happen?', 'Poor alignment and uneven shape', 'The fabric becomes polyester', 'The design brief changes'],
        ['Why organise paired pieces?', 'To keep sides, lining and matching parts clear', 'To make the table look full', 'To avoid labelling', 'Side A and side B pieces are mixed. What is the risk?', 'Incorrect assembly or decoration placement', 'Better reversibility', 'Faster evaluation']
      ], makeWritten('m8-s2', 'Write an ordered fabric-preparation and cutting checklist.', 'Begin with teacher approval and end with labelled, organised pieces.', 'First I will …; before cutting …; after cutting …', 'For a vinyl project, first confirm the approved file and material, then test scale, cut, weed carefully and label each part before assembly.')),
      makeSection('8.3 Machine readiness and practice', `
        <p>Machine readiness is demonstrated, not assumed. Identify the actual machine parts, follow the threading and bobbin sequence, check the presser foot and needle area, and complete the required teacher licence or approval.</p>
        <p>Practise straight lines, controlled curves, stopping, pivoting and reverse securing on sample fabric as directed. Record what happened and ask for help with thread nests, skipped stitches, unusual tension, broken needles or abnormal sound.</p>`, [
        ['Is machine readiness assumed?', 'No, it is demonstrated and approved', 'Yes', 'Only after watching a video', 'What may be required before production?', 'A sewing licence or teacher check', 'A mood board', 'A final evaluation'],
        ['What controls threading?', 'The actual machine’s demonstrated path', 'Any diagram online', 'The pattern symbols', 'Why identify machine parts?', 'So instructions and fault reports are precise', 'To decorate the folio', 'To choose a cause'],
        ['What should practice include?', 'Straight lines, curves, stopping and securing as directed', 'Only full-speed sewing', 'Only bobbin winding', 'Why practise curves?', 'Bucket-hat seams include curved shapes requiring control', 'Curves change fibre type', 'It makes the brim wider'],
        ['What indicates a fault?', 'Thread nests, skipped stitches, abnormal sound or needle damage', 'A tidy seam', 'A clear bobbin', 'A thread nest forms. What should the student do?', 'Stop and ask for help', 'Pull harder', 'Keep sewing'],
        ['Why record practice outcomes?', 'To identify readiness and next improvement', 'To replace teacher approval', 'To set marks', 'A sample wanders from the guide. What next?', 'Slow down and practise controlled guiding', 'Increase speed', 'Change the brief']
      ], makeWritten('m8-s3', 'Evaluate your machine-practice readiness and identify one improvement before production.', 'Use evidence from the actual sample and teacher feedback.', 'My sample shows I can …; I still need to improve … by …', 'My drill practice shows accurate entry points, but the exit splinters. I will support the underside and repeat a supervised test before the final part.'))
    ]
  },
  {
    id: 9,
    title: 'Produce the reversible hat',
    subtitle: 'Follow the authorised sequence, manage quality and record honest evidence.',
    sections: [
      makeSection('9.1 Action plan and workflow', `
        <p>An action plan orders tasks and identifies the materials, tools, checks and evidence needed. It helps a student prepare for the next practical lesson and protects time for setup, production, checking, documentation and pack-up.</p>
        <p>The plan must follow the teacher-approved construction sequence. If the actual process changes, update the plan rather than hiding the change. Record approvals and checkpoints where they genuinely occur.</p>`, [
        ['What does an action plan do?', 'Orders tasks and resources', 'Replaces the approved sequence', 'Sets official marks', 'What should each task identify?', 'Needed materials, tools, checks and evidence', 'Only a colour', 'Only a date'],
        ['Why include pack-up?', 'It is part of safe and complete practical work', 'It is optional', 'It happens automatically', 'A plan uses all lesson time for sewing. What is missing?', 'Setup, checking, evidence and pack-up time', 'More decoration', 'A new user'],
        ['Which sequence controls construction?', 'The teacher-approved project sequence', 'A generic website', 'A random tutorial', 'A video differs from the teacher demonstration. What should the student follow?', 'Teacher direction for the actual pattern and materials', 'The video', 'A combined guess'],
        ['What if the process changes?', 'Update the plan and explain why', 'Hide the change', 'Rewrite the brief', 'A technique takes longer than expected. What should be recorded?', 'The delay and revised next step', 'A false completion', 'No evidence'],
        ['What is a checkpoint?', 'A planned moment to inspect or seek approval', 'A final colour', 'A machine part', 'Before joining major sections, what may be useful?', 'A teacher alignment check', 'A new mood board', 'A copied rubric']
      ], makeWritten('m9-s1', 'Draft an action plan for your next three practical stages.', 'Name task, resources, safety check, quality check and evidence for each stage.', 'Stage 1 is …; I need …; I will check … and record …', 'For a timber joint, Stage 1 marks out the cut using a square, checks dimensions with the teacher and records a labelled photo before cutting.')),
      makeSection('9.2 Construction quality', `
        <p>Construction quality is built through accurate preparation, matched edges and notches, controlled curves, secure seams, appropriate pressing and regular checking. Reversible products need clean internal construction because either side may be visible in use.</p>
        <p>Do not continue past a problem simply to finish. Stop at puckering, mismatched seams, twisted parts or poor feeding; diagnose the cause with the teacher, test a correction where possible and record the decision.</p>`, [
        ['How is quality built?', 'Through accuracy, control and regular checking', 'Only at final evaluation', 'By sewing faster', 'Why do matched notches matter?', 'They help align curved pieces correctly', 'They decorate the seam', 'They set machine speed'],
        ['Why is reversibility demanding?', 'Either side may expose construction details', 'It needs no lining', 'It removes seams', 'An internal raw edge shows when reversed. What has failed?', 'Reversible finish quality', 'The cause research', 'The mood board'],
        ['What should happen at puckering?', 'Stop, diagnose and correct with teacher support', 'Keep sewing', 'Pull the fabric harder', 'What may cause poor curved-seam alignment?', 'Inaccurate cutting, mismatched notches or uncontrolled feeding', 'The website font', 'The user interview'],
        ['What is pressing for?', 'Shaping and controlling seams as directed', 'Replacing stitches', 'Changing fibre type', 'Why press at approved stages?', 'Some seams become difficult to access later', 'It sets the due date', 'It chooses the symbol'],
        ['Should a student hide a fault?', 'No, record and respond to it', 'Yes', 'Only in photos', 'What is strong evidence of problem-solving?', 'The fault, cause considered, action and result', 'A perfect claim', 'No explanation']
      ], makeWritten('m9-s2', 'Describe one construction problem that could occur and a safe response.', 'Use the sequence: observe → stop → diagnose → act → recheck.', 'If I observe …, I will stop and …', 'If a drilled hole starts wandering, I will stop, check clamping and alignment with the teacher, test the setup on scrap and recheck before continuing.')),
      makeSection('9.3 Progress evidence', `
        <p>Progress evidence shows real work over time. Useful evidence includes a focused photograph, date or stage label, short description of what was completed, a quality observation, a problem and the next step.</p>
        <p>Photographs should show the product or process clearly without student faces, names or private information. Evidence must be honest: a staged or example image can teach the process, but it cannot replace the student's own project record.</p>`, [
        ['What makes progress evidence useful?', 'A clear stage, observation and next step', 'A completion tick only', 'An unrelated photo', 'Which caption is stronger?', 'Brim rows completed; spacing is uneven near one seam, so I will slow down next lesson', 'Worked on hat', 'Done'],
        ['What should a photo show?', 'The relevant product or process clearly', 'Student names', 'Private Classroom information', 'Why avoid faces and names?', 'Protect privacy and keep evidence focused', 'They reduce image quality', 'They change the fabric'],
        ['Can a source photo replace student evidence?', 'No', 'Yes', 'Only if cropped', 'What can a source construction photo do?', 'Teach or clarify a stage', 'Prove the student completed it', 'Provide a grade'],
        ['What should a problem entry include?', 'Observation, response and next step', 'Only blame', 'Only a red cross', 'A seam was unpicked. What evidence helps?', 'Why it was unpicked and what improved after resewing', 'A blank photo', 'A copied caption'],
        ['Why label stages?', 'It makes the sequence and growth visible', 'It adds marks automatically', 'It hides changes', 'Photos are out of order. What should be added?', 'Stage labels or dates', 'More filters', 'A new symbol']
      ], makeWritten('m9-s3', 'Write a progress-log entry for a real or planned practical stage.', 'Include evidence, quality, problem-solving and the next action. Do not invent completed work.', 'At the … stage, I …; the evidence shows …; next I need to …', 'At the sanding stage, the edge is smoother but one pencil mark remains. Next I will sand with the approved finer abrasive and recheck before finishing.'))
    ]
  },
  {
    id: 10,
    title: 'Evaluate and communicate',
    subtitle: 'Judge the real product, respond to feedback and explain the design journey.',
    sections: [
      makeSection('10.1 Test against criteria', `
        <p>Evaluation compares the finished product with the design brief and criteria. Use evidence from fit, reversibility, message clarity, construction, comfort, durability and the intended user's response where appropriate.</p>
        <p>A judgement is stronger than a description. State the criterion, present evidence, decide the level of success and propose a specific improvement. Do not claim a test occurred if it did not.</p>`, [
        ['What does evaluation compare?', 'The product with brief and criteria', 'Only the final photo', 'Only personal taste', 'What makes a judgement strong?', 'Criterion, evidence, decision and improvement', 'A colour name', 'A mark guess'],
        ['Which evidence can test reversibility?', 'Both sides can be worn and seams remain acceptably finished', 'The title page', 'The mood board only', 'A hat reverses but feels uncomfortable. What does this show?', 'One criterion may pass while another does not', 'All criteria pass', 'Evaluation is impossible'],
        ['Should unperformed tests be claimed?', 'No', 'Yes', 'Only if likely', 'No user test occurred. What should be written?', 'That user feedback was not collected and remains a limitation', 'Invent a response', 'Copy a peer’s comment'],
        ['How should improvement be written?', 'As a specific change linked to evidence', 'As “make it better”', 'As praise only', 'Which is specific?', 'Reduce dense stitching near the brim so it bends more comfortably', 'Improve it', 'Use more design'],
        ['Can a product partly succeed?', 'Yes, criteria may produce different judgements', 'No', 'Only if unfinished', 'Why evaluate criteria separately?', 'It reveals strengths, weaknesses and trade-offs', 'It guarantees full marks', 'It avoids evidence']
      ], makeWritten('m10-s1', 'Evaluate one criterion using evidence and a specific improvement.', 'Use only a test or observation that actually occurred.', 'For the criterion …, the evidence shows …; therefore …; next time …', 'For the criterion “opens easily”, three trials showed the zip caught once at the corner. It mostly succeeded; next time I would reduce fabric bulk at that point.')),
      makeSection('10.2 Feedback and reflection', `
        <p>Peer and self-feedback can reveal how another person experiences the product. Use structured prompts: what works, what could improve, what is interesting and what next step is realistic. The designer still decides how to respond using the brief and evidence.</p>
        <p>Reflection considers growth across the whole process: early assumptions, new knowledge, skill development, decisions, problems and how thinking changed. “I used to think … now I think … because …” can make that change visible.</p>`, [
        ['What can feedback reveal?', 'How another person experiences the product', 'The official mark automatically', 'Only the designer’s intention', 'Must every suggestion be followed?', 'No, judge it against the brief and evidence', 'Yes', 'Only the longest'],
        ['What is structured feedback?', 'Specific prompts for strengths, improvements and next steps', 'A score without comment', 'A vague reaction', 'Which is structured?', 'The message is clear from the front, but side B needs more contrast', 'Nice hat', 'Cool'],
        ['What does reflection examine?', 'Growth, decisions, problems and changed thinking', 'Only the final colour', 'Only attendance', 'What completes “I used to think … now I think …”?', 'Evidence or experience that caused the change', 'A random adjective', 'A due date'],
        ['Who owns the response to feedback?', 'The designer, guided by brief and evidence', 'The loudest peer', 'The website', 'A peer asks for a copied logo. What should happen?', 'Reject the suggestion because it conflicts with originality and respect', 'Follow it', 'Hide the source'],
        ['Why include problems in reflection?', 'They show learning and problem-solving', 'They always reduce quality', 'They are private marks', 'A seam was resewn successfully. What should reflection explain?', 'What went wrong, what action worked and what was learned', 'Only that it was fixed', 'Nothing']
      ], makeWritten('m10-s2', 'Reflect on one way your thinking or skill changed during the project.', 'Name the earlier view, new view and evidence that caused the change.', 'I used to think …; now I think … because …', 'I used to think accurate cutting mattered only for appearance; now I understand it controls assembly because a small error made two trial pieces misalign.')),
      makeSection('10.3 Designer statement and presentation', `
        <p>A designer statement communicates the product's user, purpose, cause, visual choices, material and technique decisions, important challenges and final judgement. It should be concise, specific and supported by the actual hat and folio.</p>
        <p>Present clear front and reverse-side images of the real product, plus selected process evidence. Students may present verbally, in writing, by video or using another teacher-approved format. Formal submission details, marks and due dates remain <strong>Teacher to confirm</strong>.</p>`, [
        ['What should a designer statement explain?', 'User, purpose, choices, process and judgement', 'Only the student name', 'Only the price', 'What supports the statement?', 'The real product and folio evidence', 'A stock image', 'A copied campaign'],
        ['Why show both sides?', 'The reversible design must be communicated', 'To double the mark', 'Because one side is fake', 'What should product photos be?', 'Clear, honest and focused on the real hat', 'Heavily filtered', 'Taken from another project'],
        ['What presentation formats may be used?', 'Teacher-approved verbal, written, video or display formats', 'Only one online format', 'Any public post', 'Who confirms the format?', 'The teacher', 'The website', 'A random tutorial'],
        ['What remains Teacher to confirm?', 'Formal submission details, marks and due dates', 'The existence of a hat', 'The meaning of fibre', 'Why use that label?', 'The source pack does not provide a final public assessment notice', 'To avoid all assessment', 'To hide the project'],
        ['What makes a statement concise?', 'Every sentence adds specific evidence or explanation', 'It is one vague sentence', 'It repeats the brief', 'Which sentence is stronger?', 'I chose appliqué because its bold edges kept the symbol readable on both the curved crown and the intended viewing distance', 'I chose appliqué because it is good', 'My hat is nice']
      ], makeWritten('m10-s3', 'Draft a concise designer statement for your finished or planned hat.', 'Cover user, message, material/technique choice, one challenge and your judgement. Do not invent completed evidence.', 'I designed … for … to communicate …; I chose … because …', 'I designed a felt organiser for a primary student to make small tools easier to find. I chose contrasting pockets for visibility; the first handle stretched, so I reinforced it before the final test.'))
    ]
  }
];
