(() => {
  const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const container = document.querySelector('[data-folio]');
  container.innerHTML = COURSE_MODULES.map(module => `<article class="card"><p class="eyebrow">Module ${module.id}</p><h3>${module.title}</h3>${module.sections.map((section,index)=>`<div class="evidence-card"><label for="folio-${section.written.id}">${module.id}.${index+1} ${section.written.label}</label><textarea id="folio-${section.written.id}" data-save-key="buckethat:${section.written.id}" placeholder="No response saved yet."></textarea><a href="modules/module-${String(module.id).padStart(2,'0')}.html#section-${index+1}">Return to precise theory →</a></div>`).join('')}</article>`).join('');
  document.querySelectorAll('[data-save-key]').forEach(area => { area.value = localStorage.getItem(area.dataset.saveKey) || ''; area.addEventListener('input', () => localStorage.setItem(area.dataset.saveKey, area.value)); });
  document.querySelectorAll('[data-folio-meta]').forEach(field => { const key=`buckethat:folio:${field.dataset.folioMeta}`; field.value=localStorage.getItem(key)||''; field.addEventListener('input',()=>{localStorage.setItem(key,field.value);document.querySelector('[data-meta-status]').textContent='Saved on this device';}); });
  const titles=['Textiles and purpose','Safety and tools','Visual message','Brief and criteria','Mood board and concepts','Fibres and sustainability','Technique samples','Pattern and machine readiness','Action plan and progress','Evaluation and statement'];
  document.querySelector('[data-activity-summary]').innerHTML=titles.map((title,i)=>{const prefix=`buckethat:activity:a${i+1}-`;const keys=Object.keys(localStorage).filter(k=>k.startsWith(prefix)).sort();const responses=keys.map(key=>({label:localStorage.getItem(`buckethat:activity-meta:${key.slice('buckethat:activity:'.length)}`)||'Written response',value:(localStorage.getItem(key)||'').trim()})).filter(x=>x.value);return `<article class="card activity-summary-card"><h3>Activity ${i+1}: ${title}</h3><p>${responses.length?`${responses.length} response${responses.length===1?'':'s'} saved`:'Not started on this device'}</p>${responses.map(r=>`<div class="activity-evidence"><strong>${escapeHtml(r.label)}</strong><p>${escapeHtml(r.value).replace(/\n/g,'<br>')}</p></div>`).join('')}<a href="activities.html#activity-${i+1}">Open activity →</a></article>`;}).join('');
  function payload(){const values={};Object.keys(localStorage).filter(k=>k.startsWith('buckethat:')).forEach(k=>values[k]=localStorage.getItem(k));return{course:'Bucket Hat for a Cause',version:1,exportedAt:new Date().toISOString(),values};}
  document.querySelector('[data-download]').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bucket-hat-folio-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);document.querySelector('[data-file-status]').textContent='Backup downloaded.';});
  document.querySelector('#restore-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.course!=='Bucket Hat for a Cause'||!data.values)throw new Error();Object.entries(data.values).forEach(([k,v])=>{if(k.startsWith('buckethat:'))localStorage.setItem(k,String(v));});location.reload();}catch{document.querySelector('[data-file-status]').textContent='That file is not a Bucket Hat folio backup.';}});
  document.querySelector('[data-print]').addEventListener('click',()=>window.print());document.querySelector('[data-print-activities-summary]').addEventListener('click',()=>window.print());
})();
